' Developer Express Code Central Example:
' How to implement the Master-Details functionality (DataTable is a DataSource)
' 
' DataRow does not have a property that includes all child rows. So, it is
' impossible to bind the child GridControl DataSource to child rows collection via
' xaml directly. A solution is to implement a multi binding converter. In this
' converter, pass the RowHandle and the ActiveView. In the Convert method, create
' a DataView passing a child table to the DataView constructor, filter this
' DataView based by the current value of the RowHandle, return the filtered
' DataView.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E2618

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace My


	<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")> _
	Friend NotInheritable Partial Class Settings
		Inherits System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = (CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property
	End Class
End Namespace
